### ISSUE TITLE
pswp crash

### ISSUE THREAD

**Issue by jfreak** [m00s/angular-photoswipe#13]
First image loads properly but after swiping to next image all the elements under <body>element are destroyed.

**Comment by m00s** [comment]
Please give some more infos

Are you running the demo in a webserver?
Think is not working without, cause images are loaded remotely..

**Comment by jfreak** [comment]
Tried running the demo locally but failed after the second swipe..

**Comment by m00s** [comment]
@jfreak I appreciate your help, but I need more details to understand what's going on.

Did you run it in local? How?
Which browser did you use?
Which browser version and app version?

**Comment by m00s** [comment]
@jfreak Closing this for now, look at #12 if still not working for you
