### ISSUE TITLE
in the index.html why angular-photoswipe.min.js changed to angular-photoswipe.js no working?

### ISSUE THREAD

**Issue by tangtao007** [m00s/angular-photoswipe#16]

**Comment by m00s** [comment]
@happytoTom because of #11. The template is not cached in the un-minified source. You can quickly adjust the link in the source if you need to develop and test your changes.

Closing this, if you need to discuss more comment the original issue, thanks.

**Comment by tangtao007** [comment]
sorry i don't understand i change the code like this but is not working.
 var defaults = {
            baseClass: 'ng-gallery',
            thumbClass: 'ng-thumb',
            templateUrl: 'lib/ngGallery/src/html/ng-growth-view.html'
        };
        return {
            restrict: 'AE',
            replace: true,
            scope: {
                open: '=',
                options: '=',
                slides: '=',
                slideSelector: '@',
                template: '@',
                onClose: '&',
                extensions: '=?',
                type: '='
            },
            templateUrl: function (element, attrs) {
                return defaults.templateUrl;
            },

**Comment by tangtao007** [comment]
I solved the problem.
thanks...

**Comment by m00s** [comment]
Hi @happytoTom, could you please post here how you solved? So that others can find out in the future.. Thanks!
