### ISSUE TITLE
Import through JSPM failing because of "Photoswipe" dependency

### ISSUE THREAD

**Issue by olee** [m00s/angular-photoswipe#18]
Hi.
This library fails to load for me, because in the import the dependency is named `Photoswipe` instead of `photoswipe` (capital letter).

The npm import is `photoswipe` which should be correct.
See [here](https://github.com/m00s/angular-photoswipe/blob/master/angular-photoswipe.js#L114-L116)

**Comment by m00s** [comment]
@olee good catch!

Would you mind submitting a PR? It would be appreciated..

**Comment by olee** [comment]
Well... I noticed there were quite some other problems as well, so I kinda rewrote the directive from scratch...
The only thing that needs to be changed anyway is the import at the [end of the file](https://github.com/m00s/angular-photoswipe/blob/master/angular-photoswipe.js#L114-L116).

**Comment by yanbab** [comment]
same problem here, work fine on Windows and OSX not Linux ... https://github.com/m00s/angular-photoswipe/pull/20

**Comment by m00s** [comment]
I just released 0.2.0 with #20 .
Should be fine now.
