### ISSUE TITLE
Unknown provider: bProvider <- b <- ngPhotoswipeDirective

### ISSUE THREAD

**Issue by cab00m** [m00s/angular-photoswipe#2]
Hi, 

your demo script gets the error:

"Error: $injector:unpr
Unknown Provider
Unknown provider: bProvider <- b <- ngPhotoswipeDirective"

Can you help me to run the demo?

**Comment by m00s** [comment]
Hi @cab00m
The error is caused by this [2 lines](https://github.com/m00s/angular-photoswipe/blob/master/angular-photoswipe.js#L30-L31) that for now you can remove.

I'll release a fix in the next days. 
Thanks for the report

**Comment by cab00m** [comment]
Ok, thank you for your help!

**Comment by m00s** [comment]
@cab00m Minification issue. Fixed with v0.0.7.

I close this, reopen if you need
