### ISSUE TITLE
Problem with template URL

### ISSUE THREAD

**Issue by rhclayto** [m00s/angular-photoswipe#6]
While trying to use this module, I encountered an error with the default URL for the template defined in the directive.

```
function linkFn(scope, iElement, iAttrs) {
        scope.template = scope.template || 'views/ng-photoswipe.html';

        scope.$on(scope.startOn, function () {
          scope.start();
        });
```

This caused my browser to look for the template at http://example.com/views/ng-photoswipe.html, rather than within the ng-photoswipe directory (in bower_components).

**Comment by m00s** [comment]
@rhclayto I'll work on this soon, thanks

**Comment by m00s** [comment]
@rhclayto If you still have issues with the template let me know.
Here a [working fiddle](https://jsfiddle.net/m00s/adsvwq1h/1/)

**Comment by vishwas-ganguly** [comment]
Hi @m00s ,
I am still not able to run this.Can you please share a working copy
